type ReplacementMap = Record<string, string>;

const exact: ReplacementMap = {
  'Project bekijken': 'Project',
  'Bekijk project': 'Project',
  'Projectoverzicht': 'Project overview',
  'Meest recente PDF': 'Latest PDF',
  'Direct openen': 'Open now',
  'Klik op dit blok om het meest recente rapport direct te openen.': 'Tap this card to open the most recent Weld Compliance Report.',
  'Zoek op projectnaam, projectnummer of type': 'Search by project name, project number or type',
  'Zoek op projectnaam, projectnummer': 'Search by project name or project number',
  'Rapportages laden…': 'Loading reports…',
  'Rapportages laden...': 'Loading reports...',
  'Rapportage kon niet worden geladen.': 'Reports could not be loaded.',
  'Geen rapportregels gevonden.': 'No report rows found.',
  'Project onbekend': 'Project unknown',
  'PDF laden…': 'Loading PDF…',
  'PDF laden...': 'Loading PDF...',
  'PDF maken…': 'Creating PDF…',
  'PDF maken...': 'Creating PDF...',
  'PDF opnieuw aangemaakt.': 'PDF regenerated.',
  'PDF kon niet opnieuw worden aangemaakt.': 'PDF could not be regenerated.',
  'PDF preview kon niet worden geladen.': 'PDF preview could not be loaded.',
  'PDF download mislukt.': 'PDF download failed.',
  'Weld Compliance Report kon niet worden geladen.': 'Weld Compliance Report could not be loaded.',
  'Geen PDF ontvangen': 'No PDF received',
  'Download URL ontbreekt.': 'Download URL is missing.',
  'PDF URL ontbreekt.': 'PDF URL is missing.',
  'CE export tijdelijk niet beschikbaar': 'CE export temporarily unavailable',
  'Export pdf': 'Weld Compliance Report',
  'Export PDF': 'Weld Compliance Report',
  'Rapport': 'Report',
  'Rapporten': 'Reports',
  'Rapportage': 'Reports',
  'Rapportages': 'Reports',
  'Opslaan': 'Save',
  'Opslaan inspectie': 'Save & close',
  'Opslaan & sluiten': 'Save & close',
  'Opslaan…': 'Saving…',
  'Opslaan...': 'Saving...',
  'Wijzigingen opslaan': 'Save changes',
  'Opslaan wijzigingen': 'Save changes',
  'Project wijzigen': 'Update project',
  'Las aanmaken': 'Create weld',
  'weld aanmaken': 'Create weld',
  'Terug': 'Back',
  'Terug naar lassen': 'Back to welds',
  'Annuleren': 'Cancel',
  'Bewerken': 'Edit',
  'Wijzigen': 'Edit',
  'Verwijderen': 'Delete',
  'Nieuw': 'New',
  'Nieuwe las': 'Create weld',
  'Nieuwe assemblage': 'Create assembly',
  'Nieuw project': 'Create project',
  'Projecten': 'Projects',
  'Project': 'Project',
  'Projectnaam': 'Project name',
  'Projectnummer': 'Project number',
  'Startdatum': 'Start date',
  'Einddatum': 'End date',
  'Lassen': 'Welds',
  'Las': 'Weld',
  'Las bewerken': 'Edit weld',
  'Lasnummer': 'Weld number',
  'Lasdatum': 'Weld date',
  'Lasmethode': 'Welding process',
  'Lasser': 'Welder',
  'Lassers': 'Welders',
  'Lascoördinator': 'Welding coordinator',
  'Lascoordinator': 'Welding coordinator',
  'Assemblage': 'Assembly',
  'Assemblages': 'Assemblies',
  'Inspectie': 'Inspection',
  'Inspecties': 'Inspections',
  'Lascontrole': 'Weld inspection',
  'Visuele inspectie': 'Visual inspection',
  'Inspectietemplate': 'Inspection template',
  'Inspectietemplates': 'Inspection templates',
  'Inspectiecontrole': 'Inspection item',
  'Inspectie laden…': 'Loading inspection…',
  'Inspectie laden...': 'Loading inspection...',
  'Lassen laden…': 'Loading weld data…',
  'Las laden…': 'Loading weld data…',
  'Project laden…': 'Loading project…',
  'Gegevens worden bijgewerkt…': 'Updating data…',
  'Geen locatie': 'No location',
  'Geen bestanden ontvangen': 'No files uploaded',
  'Geen preview beschikbaar.': 'No preview available.',
  'Geen toegang tot deze tenant': 'No access to this tenant',
  'Status': 'Status',
  'Tenantstatus': 'Tenant status',
  'Laatste update': 'Last updated',
  'Conform': 'Compliant',
  'Niet conform': 'Non-compliant',
  'Non-conform': 'Non-compliant',
  'In controle': 'In control',
  'Gerepareerd': 'Repaired',
  'Actief': 'Active',
  'Inactief': 'Inactive',
  'Gesuspendeerd': 'Suspended',
  'Ingekocht': 'Purchased',
  'Automatisch volgens EXC': 'Automatic based on EXC',
  'Gekoppelde users': 'Linked users',
  'Gekoppelde tenant-users': 'Linked tenant users',
  'Open': 'Open',
  'Executieklasse': 'Execution class',
  'Tekeningen / lasplan aanwezig': 'Drawings / weld plan available',
  'Materiaaltraceerbaarheid vastgelegd': 'Material traceability documented',
  'Juiste WPS / WPQR toegepast': 'Correct WPS / WPQR applied',
  'Opmerking': 'Remarks',
  'Opmerkingen': 'Remarks',
  'Algemene opmerkingen': 'General remarks',
  'Toelichting': 'Explanation',
  'Toelichting / notitie': 'Explanation / note',
  'Optionele waarde': 'Optional value',
  'Optionele opmerking': 'Optional remarks',
  'Optionele opmerking voor deze inspectie': 'Optional remarks for this inspection',
  'Opmerking toevoegen': 'Add remarks',
  'Algemene inspectie-opmerking toevoegen': 'Add general inspection remarks',
  'Selecteer template': 'Select template',
  'Selecteer assemblage': 'Select assembly',
  'Selecteer materiaal': 'Select material',
  'Selecteer lasser': 'Select welder',
  'Selecteer WPS': 'Select WPS',
  'Selecteer lascoördinator': 'Select welding coordinator',
  'Foto’s toevoegen': 'Add photos',
  'Fotos toevoegen': 'Add photos',
  'Camera of fotobibliotheek': 'Camera or photo library',
  'Voeg extra foto’s toe aan deze las': 'Add supporting photos to this weld',
  'Foto verwijderen': 'Delete photo',
  'Bestand': 'File',
  'Bestanden': 'Files',
  'Documenten': 'Documents',
  'Documenten gekoppeld': 'Documents linked',
  'Documenten toevoegen': 'Add documents',
  'Instellingen': 'Settings',
  'Dashboard': 'Dashboard',
  'Facturatie': 'Billing',
  'Facturen': 'Invoices',
  'Factuur': 'Invoice',
  'Gebruiker': 'User',
  'Gebruikers': 'Users',
  'Wachtwoord': 'Password',
  'Inloggen': 'Sign in',
  'Uitloggen': 'Sign out',
  'E-mailadres': 'Email address',
  'Wachtwoord vergeten': 'Forgot your password?',
  'Wachtwoord instellen': 'Create password',
  'Wachtwoord wijzigen': 'Change password',
  'Account activeren': 'Activate account',
  'Zoeken': 'Search',
  'Zoek tenant, id, billing of status': 'Search tenant, id, billing or status',
  'Filter': 'Filter',
  'Filters': 'Filters',
  'Kolommen': 'Columns',
  'Naam': 'Name',
  'Omschrijving': 'Description',
  'Opdrachtgever': 'Client',
  'Contactpersoon': 'Contact person',
  'Aanmaken': 'Create',
  'Bijwerken': 'Update',
  'Sluiten': 'Close',
  'Bekijken': 'View',
  'Bekijk PDF': 'View PDF',
  'Downloaden': 'Download',
  'Uploaden': 'Upload',
  'Toevoegen': 'Add',
  'Project 360': 'Project overview',
  'CE Dossier': 'CE Dossier',
  'Samenvatting': 'Summary',
  'Rechten': 'Permissions',
  'Groei': 'Growth',
  'Statusbeheer': 'Status management',
  'Platformcontrole': 'Platform control',
  'Nieuwe tenant': 'Create tenant',
  'Tenantbeheer': 'Tenant management',
  'Alle tenants in platform': 'All tenants in platform',
  'Direct inzetbaar': 'Ready to use',
  'Health en contracten': 'Health and contracts',
  'Omgeving': 'Environment',
  'Aangemaakt': 'Created',
  'Acties': 'Actions',
  'Meekijken': 'View tenant',
  'Activeer': 'Activate',
  'Heractiveer': 'Reactivate',
  'Verlaat tenant-view': 'Exit tenant view',
  'Tenant-view actief': 'Tenant view active',
  'Tenant-view mislukt': 'Tenant view failed',
  'Alle statussen': 'All statuses',
  'Jaarabonnement WeldInspect': 'Annual WeldInspect subscription',
  'Creditnota door superadmin': 'Credit note by superadmin',
  'Geen tenants': 'No tenants',
  'Tenants laden...': 'Loading tenants...',
  'Health controleren...': 'Checking health...',
  'Health niet bereikbaar': 'Health unavailable',
  'Platform online': 'Platform online',
  'Health-check fout': 'Health check error',
  'Alleen lezen': 'Read only',
  'Impersonatie actief': 'Impersonation active',
  'Nog geen lassen in dit project.': 'No welds have been created for this project yet.',
  'Lasnummer is verplicht.': 'Weld number is required.',
  'Inspectie opslaan mislukt.': 'Could not save the inspection.',
  'Inspectie kon niet worden geladen.': 'The inspection could not be loaded.',
  'Inspectie kon niet worden opgeslagen.': 'Inspection could not be saved.',
  'Inspectie opgeslagen.': 'Inspection saved.',
  'Las opslaan mislukt.': 'Could not save the weld.',
  'Las kon niet worden geladen.': 'The weld could not be loaded.',
  'Lassen konden niet worden geladen.': 'Weld data could not be loaded.',
  'Werk lasgegevens bij': 'Update weld details',
  'Werk projectgegevens bij': 'Update project details',
  'Maak een nieuwe las aan': 'Create a new weld',
  'Maak een nieuw project aan': 'Create a new project',
  'Controleer de las visueel op onderstaande punten.': 'Visually check the weld against the items below.',
  'Datum': 'Date',
  'Locatie': 'Location',
  'Materiaal': 'Material',
  'Klant': 'Customer',
  'Bedrijf': 'Company',
  'Proefperiode': 'Trial',
  'Abonnement': 'Subscription',
  'Betaling': 'Payment',
  'Betaald': 'Paid',
  'Openstaand': 'Open',
  'Verlopen': 'Expired',
  'Mislukt': 'Failed',
  'Gelukt': 'Succeeded',
  'Volgende': 'Next',
  'Vorige': 'Previous',
  'Doorgaan': 'Continue',
  'Verzenden': 'Send',
  'Bevestigen': 'Confirm',
  'Resetten': 'Reset',
  'Vernieuwen': 'Refresh',
  'Kopiëren': 'Copy',
  'Gekopieerd': 'Copied',
  'Laden…': 'Loading…',
  'Laden...': 'Loading...',
};

const phrasePairs: Array<[RegExp, string]> = [
  [/\bProject bekijken\b/g, 'Project'],
  [/\bBekijk project\b/g, 'Project'],
  [/\bProjectoverzicht\b/g, 'Project overview'],
  [/\bMeest recente PDF\b/g, 'Latest PDF'],
  [/\bDirect openen\b/g, 'Open now'],
  [/Klik op dit blok om het meest recente rapport direct te openen\./g, 'Tap this card to open the most recent Weld Compliance Report.'],
  [/\bZoek op projectnaam, projectnummer of type\b/g, 'Search by project name, project number or type'],
  [/\bZoek op projectnaam, projectnummer\b/g, 'Search by project name or project number'],
  [/\bRapportages laden…\b/g, 'Loading reports…'],
  [/\bRapportages laden\.\.\.\b/g, 'Loading reports...'],
  [/\bRapportage kon niet worden geladen\./g, 'Reports could not be loaded.'],
  [/\bGeen rapportregels gevonden\./g, 'No report rows found.'],
  [/\bProject onbekend\b/g, 'Project unknown'],
  [/\bExport pdf\b/gi, 'Weld Compliance Report'],
  [/\bProject\s+overview\s+(\d+)/gi, 'Weld Compliance Report $1'],
  [/\bProjectoverzicht\s+(\d+)/g, 'Weld Compliance Report $1'],
  [/\bPDF maken…\b/g, 'Creating PDF…'],
  [/\bPDF maken\.\.\.\b/g, 'Creating PDF...'],
  [/\bPDF laden…\b/g, 'Loading PDF…'],
  [/\bPDF laden\.\.\.\b/g, 'Loading PDF...'],
  [/\bOpslaan & sluiten\b/g, 'Save & close'],
  [/\bOpslaan inspectie\b/g, 'Save & close'],
  [/\bProject wijzigen\b/g, 'Update project'],
  [/\bweld aanmaken\b/gi, 'Create weld'],
  [/\bNieuwe las\b/g, 'Create weld'],
  [/\bNieuw project\b/g, 'Create project'],
  [/\bNieuwe assemblage\b/g, 'Create assembly'],
  [/\bNieuwe\b/g, 'New'],
  [/\bOpslaan\b/g, 'Save'],
  [/\bTerug naar\b/g, 'Back to'],
  [/\bBewerken\b/g, 'Edit'],
  [/\bWijzigen\b/g, 'Edit'],
  [/\bVerwijderen\b/g, 'Delete'],
  [/\bAnnuleren\b/g, 'Cancel'],
  [/\bNiet conform\b/g, 'Non-compliant'],
  [/\bNon-conform\b/g, 'Non-compliant'],
  [/\bIn controle\b/g, 'In control'],
  [/\bConform\b/g, 'Compliant'],
  [/\bGerepareerd\b/g, 'Repaired'],
  [/\bActief\b/g, 'Active'],
  [/\bInactief\b/g, 'Inactive'],
  [/\bGesuspendeerd\b/g, 'Suspended'],
  [/\bIngekocht\b/g, 'Purchased'],
  [/\bAutomatisch volgens EXC\b/g, 'Automatic based on EXC'],
  [/\bGekoppelde users\b/g, 'Linked users'],
  [/\bGekoppelde tenant-users\b/g, 'Linked tenant users'],
  [/\bTenantstatus\b/g, 'Tenant status'],
  [/\bLascontrole\b/g, 'Weld inspection'],
  [/\bVisuele inspectie\b/g, 'Visual inspection'],
  [/\bLassen\b/g, 'Welds'],
  [/\bLasnummer\b/g, 'Weld number'],
  [/\bLasdatum\b/g, 'Weld date'],
  [/\bLasmethode\b/g, 'Welding process'],
  [/\bLascoördinator\b/g, 'Welding coordinator'],
  [/\bLascoordinator\b/g, 'Welding coordinator'],
  [/\bLassers\b/g, 'Welders'],
  [/\bLasser\b/g, 'Welder'],
  [/\blas\b/gi, 'weld'],
  [/\bInspectietemplates\b/g, 'Inspection templates'],
  [/\bInspectiecontrole\b/g, 'Inspection item'],
  [/\bInspectietemplate\b/g, 'Inspection template'],
  [/\bInspecties\b/g, 'Inspections'],
  [/\bInspectie\b/g, 'Inspection'],
  [/\bProject 360\b/g, 'Project overview'],
  [/\bProjectnaam\b/g, 'Project name'],
  [/\bProjectnummer\b/g, 'Project number'],
  [/\bProjecten\b/g, 'Projects'],
  [/\bInstellingen\b/g, 'Settings'],
  [/\bGeen bestanden ontvangen\b/g, 'No files uploaded'],
  [/\bGeen preview beschikbaar\b/g, 'No preview available'],
  [/\bGeen\b/g, 'No'],
  [/\bSelecteer\b/g, 'Select'],
  [/\bAlgemene opmerkingen\b/g, 'General remarks'],
  [/\bOpmerkingen\b/g, 'Remarks'],
  [/\bOpmerking\b/g, 'Remarks'],
  [/\bToelichting\b/g, 'Explanation'],
  [/\bNotitie\b/g, 'Note'],
  [/\bMateriaaltraceerbaarheid\b/g, 'Material traceability'],
  [/\bMateriaal\b/g, 'Material'],
  [/\bDocumenten\b/g, 'Documents'],
  [/\bDocument\b/g, 'Document'],
  [/\bFoto’s\b/g, 'Photos'],
  [/\bFotos\b/g, 'Photos'],
  [/\bFoto\b/g, 'Photo'],
  [/\bGebruikers\b/g, 'Users'],
  [/\bGebruiker\b/g, 'User'],
  [/\bWachtwoord vergeten\b/g, 'Forgot your password?'],
  [/\bWachtwoord instellen\b/g, 'Create password'],
  [/\bWachtwoord wijzigen\b/g, 'Change password'],
  [/\bWachtwoord\b/g, 'Password'],
  [/\bInloggen\b/g, 'Sign in'],
  [/\bUitloggen\b/g, 'Sign out'],
  [/\bOpdrachtgever\b/g, 'Client'],
  [/\bContactpersoon\b/g, 'Contact person'],
  [/\bAangemaakt\b/g, 'Created'],
  [/\bLaatste update\b/g, 'Last updated'],
  [/\bLaatst\b/g, 'Last'],
  [/\blaatste\b/g, 'last'],
  [/\bLocatie\b/g, 'Location'],
  [/\bDatum\b/g, 'Date'],
  [/\bBedrijf\b/g, 'Company'],
  [/\bKlant\b/g, 'Customer'],
  [/\bFacturen\b/g, 'Invoices'],
  [/\bFactuur\b/g, 'Invoice'],
  [/\bFacturatie\b/g, 'Billing'],
  [/\bProefperiode\b/g, 'Trial'],
  [/\bAbonnement\b/g, 'Subscription'],
  [/\bBetaling\b/g, 'Payment'],
  [/\bBetaald\b/g, 'Paid'],
  [/\bOpenstaand\b/g, 'Open'],
  [/\bVerlopen\b/g, 'Expired'],
  [/\bMislukt\b/g, 'Failed'],
  [/\bGelukt\b/g, 'Succeeded'],
  [/\bVolgende\b/g, 'Next'],
  [/\bVorige\b/g, 'Previous'],
  [/\bDoorgaan\b/g, 'Continue'],
  [/\bVerzenden\b/g, 'Send'],
  [/\bBevestigen\b/g, 'Confirm'],
  [/\bResetten\b/g, 'Reset'],
  [/\bVernieuwen\b/g, 'Refresh'],
  [/\bKopiëren\b/g, 'Copy'],
  [/\bGekopieerd\b/g, 'Copied'],
  [/\bAanmaken\b/g, 'Create'],
  [/\bBijwerken\b/g, 'Update'],
  [/\bSluiten\b/g, 'Close'],
  [/\bBekijken\b/g, 'View'],
  [/\bDownloaden\b/g, 'Download'],
  [/\bUploaden\b/g, 'Upload'],
  [/\bToevoegen\b/g, 'Add'],
  [/\bZoeken\b/g, 'Search'],
];

function translateText(input: string): string {
  const trimmed = input.trim();
  if (!trimmed) return input;
  const direct = exact[trimmed];
  if (direct) return input.replace(trimmed, direct);
  let output = input;
  for (const [pattern, replacement] of phrasePairs) output = output.replace(pattern, replacement);
  return output;
}

function shouldSkipElement(element: Element | null): boolean {
  if (!element) return false;
  const tag = element.tagName.toLowerCase();
  return tag === 'script' || tag === 'style' || tag === 'code' || tag === 'pre' || element.hasAttribute('data-no-translate');
}

function translateAttributes(element: Element): void {
  if (shouldSkipElement(element)) return;
  for (const attr of ['placeholder', 'aria-label', 'title', 'alt']) {
    const value = element.getAttribute(attr);
    if (value) element.setAttribute(attr, translateText(value));
  }
}

function translateNode(node: Node): void {
  if (node.nodeType === Node.TEXT_NODE) {
    const parent = node.parentElement;
    if (shouldSkipElement(parent)) return;
    const next = translateText(node.textContent || '');
    if (next !== node.textContent) node.textContent = next;
    return;
  }
  if (node.nodeType === Node.ELEMENT_NODE) {
    const element = node as Element;
    translateAttributes(element);
    element.childNodes.forEach(translateNode);
  }
}

export function installFrontendEnglish(): void {
  if (typeof window === 'undefined' || typeof document === 'undefined') return;
  const run = () => translateNode(document.body);
  if (document.readyState === 'loading') document.addEventListener('DOMContentLoaded', run, { once: true });
  else run();
  const observer = new MutationObserver((mutations) => {
    for (const mutation of mutations) {
      mutation.addedNodes.forEach(translateNode);
      if (mutation.type === 'characterData') translateNode(mutation.target);
    }
  });
  observer.observe(document.documentElement, { childList: true, subtree: true, characterData: true });
}
