
(function(){
  function rootPrefix(){ const href=String(location.href||''); return (href.includes('/layers/')||href.includes('\\layers\\')) ? '..' : '.'; }
  const root = rootPrefix();
  const loginUrl = root + '/login.html';
  function currentNext(){ const u=new URL(location.href); return u.pathname + (u.search||'') + (u.hash||''); }
  function injectLoader(){ if(document.getElementById('authLoader')) return; document.documentElement.classList.add('auth-pending'); const wrap=document.createElement('div'); wrap.className='auth-loader'; wrap.id='authLoader'; wrap.innerHTML='<div class="auth-loader-card"><div class="auth-spinner"></div><div><strong>Sessie controleren...</strong><div style="color:#62708a;font-size:14px;margin-top:2px">Beveiligde pagina wordt geladen</div></div></div>'; document.addEventListener('DOMContentLoaded',()=>document.body.appendChild(wrap),{once:true}); }
  function clearLoader(){ document.documentElement.classList.remove('auth-pending'); const el=document.getElementById('authLoader'); if(el) el.remove(); }
  function showError(title,msg){ clearLoader(); const el=document.createElement('div'); el.className='guard-error-screen'; el.innerHTML='<div class="guard-error-card"><h2>'+title+'</h2><p>'+msg+'</p><div class="guard-error-actions"><button id="guardRetryBtn">Opnieuw proberen</button><a href="'+root+'/layers/dashboard.html">Ga naar dashboard</a><a href="'+loginUrl+'">Ga naar login</a></div></div>'; document.addEventListener('DOMContentLoaded',()=>{document.body.appendChild(el); const btn=document.getElementById('guardRetryBtn'); if(btn) btn.addEventListener('click',()=>location.reload());},{once:true}); }
  async function bootstrap(){ injectLoader(); if(!window.Auth){ window.addEventListener('load', bootstrap, {once:true}); return; } const hasToken = !!((window.Auth.getAccessToken&&window.Auth.getAccessToken()) || localStorage.getItem('nen1090.auth.access') || localStorage.getItem('auth_token')); const hasRefresh = !!(window.Auth.getRefreshToken&&window.Auth.getRefreshToken()); if(!hasToken && !hasRefresh){ location.replace(loginUrl + '?next=' + encodeURIComponent(currentNext())); return; } try { const me = await window.Auth.me(); if(!me || !me.email){ throw new Error('NO_USER'); } window.__AUTH_ME__ = me; clearLoader(); } catch(err){ if(err && (err.status===401 || String(err.message||'').includes('401') || String(err.message||'').includes('NO_USER'))){ try{ window.Auth.clearTokens && window.Auth.clearTokens(); }catch(_){ } location.replace(loginUrl + '?next=' + encodeURIComponent(currentNext())); return; } if(err && (err.code==='API_OFFLINE' || String(err.message||'').includes('API_OFFLINE'))){ showError('Verbinding met server mislukt','De app kan de server nu niet bereiken. Probeer opnieuw of ga terug naar de loginpagina.'); return; } showError('Sessie kon niet worden gecontroleerd','Er is een probleem opgetreden bij het laden van je sessie. Probeer opnieuw of log opnieuw in.'); } }
  window.AppGuard = { bootstrap: bootstrap }; bootstrap();
})();
